apiVersion: v2
name: openg2p-g2p-bridge
description: A Helm chart for OpenG2P G2P Bridge
type: application
version: 1.0.2
appVersion: ""
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
  condition: common.enabled
- name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 15.x.x
  condition: postgresql.enabled
- name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 20.x.x
  condition: redis.enabled
- name: openg2p-g2p-bridge-api
  version: 1.0.0
  condition: openg2p-g2p-bridge-api.enabled
- name: openg2p-g2p-bridge-celery-beat-producers
  version: 1.0.0
  condition: openg2p-g2p-bridge-celery-beat-producers.enabled
- name: openg2p-g2p-bridge-celery-workers
  version: 1.0.0
  condition: openg2p-g2p-bridge-celery-workers.enabled
keywords:
  - openg2p-g2p-bridge-api
maintainers:
  - email: info@openg2p.org
    name: OpenG2P
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
annotations:
  catalog.cattle.io/display-name: "OpenG2P-G2P-Bridge"
