apiVersion: v2
name: openg2p-g2p-bridge
description: A Helm chart for OpenG2P G2P Bridge
type: application
version: 2.0.0
dependencies:
- name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 15.x.x
  condition: postgresql.enabled
- name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 19.x.x
  condition: redis.enabled
- name: artifactory
  version: 12.0.2
  repository: https://openg2p.github.io/openg2p-helm
  condition: artifactory.enabled
- name: keymanager
  version: 12.1.0
  repository: https://openg2p.github.io/openg2p-helm
  condition: keymanager.enabled
- name: softhsm
  repository: https://mosip.github.io/mosip-helm
  version: 12.0.1
  condition: softhsm.enabled
- name: openg2p-g2p-bridge-api
  version: 2.0.0
  condition: openg2p-g2p-bridge-api.enabled
- name: openg2p-g2p-bridge-celery-beat-producers
  version: 2.0.0
  condition: openg2p-g2p-bridge-celery-beat-producers.enabled
- name: openg2p-g2p-bridge-celery-workers
  version: 2.0.0
  condition: openg2p-g2p-bridge-celery-workers.enabled
keywords:
  - openg2p-g2p-bridge
  - openg2p-g2p-bridge-api
  - openg2p-g2p-bridge-celery-beat-producers
  - openg2p-g2p-bridge-celery-workers
  - g2p-bridge
maintainers:
  - email: info@openg2p.org
    name: OpenG2P
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
annotations:
  catalog.cattle.io/display-name: "OpenG2P G2P Bridge"
  openg2p.org/add-to-rancher: ""
