global:
  g2pBridgeHostname: g2p-bridge.openg2p.sandbox.net

  g2pBridgeExampleBankBaseUrl: http://openg2p-g2p-bridge-example-bank-api

  keycloakBaseUrl: https://keycloak.your.org
  keycloakIssuerUrl: '{{ tpl .Values.global.keycloakBaseUrl $ }}/realms/master'

  g2pBridgeClientId: 'openg2p-g2p-bridge-{{ .Release.Namespace }}'
  g2pBridgeClientSecret: ''

  keymanagerAuthEnabled: false
  keymanagerG2pBridgeAppId: OPENG2P_G2P_BRIDGE

openg2p-g2p-bridge-api:
  enabled: true
  nameOverride: api

  keymanagerInstallationName: '{{ .Release.Name }}-keymanager'

  envVars:
    G2P_BRIDGE_JWT_VALIDATE_KEYMANAGER_APP_ID: '{{ tpl .Values.global.keymanagerG2pBridgeAppId $ }}'

    G2P_BRIDGE_KEYMANAGER_API_BASE_URL: "http://{{ tpl .Values.keymanagerInstallationName $ }}/v1/keymanager"
    G2P_BRIDGE_KEYMANAGER_AUTH_ENABLED: '{{ .Values.global.keymanagerAuthEnabled }}'
    G2P_BRIDGE_KEYMANAGER_AUTH_URL: "{{ tpl .Values.global.keycloakIssuerUrl $ }}/protocol/openid-connect/token"
    G2P_BRIDGE_KEYMANAGER_AUTH_CLIENT_ID: '{{ tpl .Values.global.g2pBridgeClientId $ }}'
    G2P_BRIDGE_KEYMANAGER_AUTH_CLIENT_SECRET: '{{ tpl .Values.global.g2pBridgeClientSecret $ }}'

openg2p-g2p-bridge-celery-beat-producers:
  enabled: true
  nameOverride: celery-beat-producer
  envVars:
    G2P_BRIDGE_CELERY_BEAT_MAPPER_RESOLVE_FREQUENCY: 10
    G2P_BRIDGE_CELERY_BEAT_FUNDS_AVAILABLE_CHECK_FREQUENCY: 10
    G2P_BRIDGE_CELERY_BEAT_FUNDS_BLOCKED_FREQUENCY: 10
    G2P_BRIDGE_CELERY_BEAT_FUNDS_DISBURSEMENT_FREQUENCY: 10
    G2P_BRIDGE_CELERY_BEAT_MT940_PROCESSOR_FREQUENCY: 10

openg2p-g2p-bridge-celery-workers:
  enabled: true
  nameOverride: celery-worker

  keymanagerInstallationName: '{{ .Release.Name }}-keymanager'

  envVars:
    G2P_BRIDGE_CELERY_WORKERS_MAPPER_RESOLVE_API_URL: 'http://spar-spar-mapper-api/sync/resolve'

    G2P_BRIDGE_CELERY_PRODUCERS_FUNDS_AVAILABLE_CHECK_URL_EXAMPLE_BANK: '{{ tpl .Values.global.g2pBridgeExampleBankBaseUrl $ }}/check_funds'
    G2P_BRIDGE_CELERY_PRODUCERS_FUNDS_BLOCK_URL_EXAMPLE_BANK: '{{ tpl .Values.global.g2pBridgeExampleBankBaseUrl $ }}/block_funds'
    G2P_BRIDGE_CELERY_PRODUCERS_FUNDS_DISBURSEMENT_URL_EXAMPLE_BANK: '{{ tpl .Values.global.g2pBridgeExampleBankBaseUrl $ }}/initiate_payment'

    G2P_BRIDGE_CELERY_WORKERS_SIGN_KEY_KEYMANAGER_APP_ID: '{{ tpl .Values.global.keymanagerG2pBridgeAppId $ }}'

    G2P_BRIDGE_CELERY_WORKERS_KEYMANAGER_API_BASE_URL: 'http://{{ tpl .Values.keymanagerInstallationName $ }}/v1/keymanager'
    G2P_BRIDGE_CELERY_WORKERS_KEYMANAGER_AUTH_ENABLED: '{{ .Values.global.keymanagerAuthEnabled }}'
    G2P_BRIDGE_CELERY_WORKERS_KEYMANAGER_AUTH_URL: '{{ tpl .Values.global.keycloakIssuerUrl $ }}/protocol/openid-connect/token'
    G2P_BRIDGE_CELERY_WORKERS_KEYMANAGER_AUTH_CLIENT_ID: '{{ tpl .Values.global.g2pBridgeClientId $ }}'
    G2P_BRIDGE_CELERY_WORKERS_KEYMANAGER_AUTH_CLIENT_SECRET: '{{ tpl .Values.global.g2pBridgeClientSecret $ }}'

postgresql:
  enabled: true
  auth:
    username: bridgeuser
    database: openg2p_g2p_bridge_db
  additionalDbs:
    enabled: true
    userPasswordsExistingSecret: ""
    userPasswords:
      keymgruser: ""
  primary:
    resourcesPreset: "small"
    extendedConfiguration: |-
      wal_level = logical
      max_wal_senders = 20
      max_replication_slots = 10

redis:
  enabled: true
  architecture: standalone
  master:
    persistence:
      enabled: false
  auth:
    enabled: false

artifactory:
  enabled: false
  image:
    repository: mosipid/artifactory-server
    tag: 1.4.1-ES
  resources: {}

softhsm:
  enabled: false
  # Hardcoding this for now. else every upgrade will reset the pin
  securityPIN: MTg5MTAwMTc=
  resources: {}

keymanager:
  enabled: true
  hostname: '{{ tpl .Values.global.g2pBridgeHostname $ }}'
  authEnabled: '{{ .Values.global.keymanagerAuthEnabled }}'
  istio:
    enabled: true
  keystoreType: PKCS12
  springConfig:
    names: application,kernel
    profile: default
    gitRepo:
      enabled: true
      repoUrl: https://github.com/openg2p/mosip-config
      branch: master
    rawConfig: ""
  envVars:
    auth_server_admin_allowed_audience: 'openg2p-g2p-bridge,openg2p-g2p-bridge-{{ .Release.Namespace }}'
  envVarsFrom:
    db_dbuser_password:
      secretKeyRef:
        name: '{{ .Release.Name }}-postgresql-addl-user-passwords'
        key: keymgruser
  postgresInit:
    envVarsFrom:
      DBUSER_PWD:
        secretKeyRef:
          name: '{{ .Release.Name }}-postgresql-addl-user-passwords'
          key: keymgruser
  keygen:
    appIdsList:
      - '{{ tpl .Values.global.keymanagerG2pBridgeAppId $ }}'
    baseKeysList:
      - '{{ tpl .Values.global.keymanagerG2pBridgeAppId $ }}:ENCRYPT'
  persistence:
    enabled: true
