global:
  g2pBridgeHostname: g2p-bridge.sandbox.openg2p.net

  g2pBridgeExampleBankBaseUrl: http://openg2p-g2p-bridge-example-bank-api

openg2p-g2p-bridge-api:
  enabled: true
  nameOverride: api

openg2p-g2p-bridge-celery-beat-producers:
  enabled: true
  nameOverride: celery-beat-producer
  envVars:
    G2P_BRIDGE_CELERY_BEAT_MAPPER_RESOLVE_FREQUENCY: 10
    G2P_BRIDGE_CELERY_BEAT_FUNDS_AVAILABLE_CHECK_FREQUENCY: 10
    G2P_BRIDGE_CELERY_BEAT_FUNDS_BLOCKED_FREQUENCY: 10
    G2P_BRIDGE_CELERY_BEAT_FUNDS_DISBURSEMENT_FREQUENCY: 10
    G2P_BRIDGE_CELERY_BEAT_MT940_PROCESSOR_FREQUENCY: 10

openg2p-g2p-bridge-celery-workers:
  enabled: true
  nameOverride: celery-worker
  envVars:
    G2P_BRIDGE_CELERY_WORKERS_MAPPER_RESOLVE_API_URL: 'http://spar-spar-mapper-api/sync/resolve'

    G2P_BRIDGE_CELERY_WORKERS_BANK_FA_DECONSTRUCT_STRATEGY: ^account_number:(?P<account_number>.*)\.branch_code:(?P<branch_code>.*)\.bank_code:(?P<bank_code>.*)\.mobile_number:(?P<mobile_number>.*)\.email_address:(?P<email_address>.*)\.fa_type:(?P<fa_type>.*)$
    G2P_BRIDGE_CELERY_WORKERS_MOBILE_WALLET_DECONSTRUCT_STRATEGY: ^mobile_number:(?P<mobile_number>.*)\.wallet_provider_name:(?P<wallet_provider_name>.*)\.wallet_provider_code:(?P<wallet_provider_code>.*)\.fa_type:(?P<fa_type>.*)$
    G2P_BRIDGE_CELERY_WORKERS_EMAIL_WALLET_DECONSTRUCT_STRATEGY: ^email_address:(?P<email_address>.*)\.wallet_provider_name:(?P<wallet_provider_name>.*)\.wallet_provider_code:(?P<wallet_provider_code>.*)\.fa_type:(?P<fa_type>.*)$

    G2P_BRIDGE_CELERY_PRODUCERS_FUNDS_AVAILABLE_CHECK_URL_EXAMPLE_BANK: '{{ tpl .Values.global.g2pBridgeExampleBankBaseUrl $ }}/check_funds'
    G2P_BRIDGE_CELERY_PRODUCERS_FUNDS_BLOCK_URL_EXAMPLE_BANK: '{{ tpl .Values.global.g2pBridgeExampleBankBaseUrl $ }}/block_funds'
    G2P_BRIDGE_CELERY_PRODUCERS_FUNDS_DISBURSEMENT_URL_EXAMPLE_BANK: '{{ tpl .Values.global.g2pBridgeExampleBankBaseUrl $ }}/initiate_payment'

postgresql:
  enabled: true
  auth:
    username: bridgeuser
    database: openg2p_g2p_bridge_db
  additionalDbs:
    enabled: true
    userPasswordsExistingSecret: ""
    userPasswords:
      keymgruser: ""
  primary:
    resourcesPreset: "small"
    extendedConfiguration: |-
      wal_level = logical
      max_wal_senders = 20
      max_replication_slots = 10

redis:
  enabled: true
  architecture: standalone
  master:
    persistence:
      enabled: false
  auth:
    enabled: false

artifactory:
  enabled: true
  image:
    repository: mosipid/artifactory-server
    tag: 1.4.1-ES
  resources: {}

softhsm:
  enabled: true
  # Hardcoding this for now. else every upgrade will reset the pin
  securityPIN: MTg5MTAwMTc=
  resources: {}

keymanager:
  enabled: true
  hostname: '{{ tpl .Values.global.g2pBridgeHostname $ }}'
  springConfig:
    names: application,kernel
    profile: default
    gitRepo:
      enabled: true
      repoUrl: https://github.com/openg2p/mosip-config
      branch: master
    rawConfig: ""
  envVars:
    mosip_kernel_keymanager_autogen_appids_list: ROOT,G2PBRIDGE
    mosip_kernel_keymanager_autogen_basekeys_list: 'G2PBRIDGE:ENCRYPT'
    auth_server_admin_allowed_audience: 'openg2p-g2p-bridge,openg2p-g2p-bridge-{{ .Release.Namespace }}'
  envVarsFrom:
    db_dbuser_password:
      secretKeyRef:
        name: '{{ .Release.Name }}-postgresql-addl-user-passwords'
        key: keymgruser
  postgresInit:
    commonAnnotations:
      "helm.sh/hook-weight": "0"
    envVarsFrom:
      DBUSER_PWD:
        secretKeyRef:
          name: '{{ .Release.Name }}-postgresql-addl-user-passwords'
          key: keymgruser
  keygen:
    commonAnnotations:
      "helm.sh/hook-weight": "1"
