openg2p-g2p-bridge-api:
  enabled: true
  common:
    enabled: false
  postgresql:
    enabled: false
  envVars:
    G2P_BRIDGE_DB_HOSTNAME: '{{ .Release.Name }}-postgresql'
  envVarsFrom:
    G2P_BRIDGE_DB_PASSWORD:
      secretKeyRef:
        name: '{{ .Release.Name }}-postgresql'
        key: password

openg2p-g2p-bridge-celery-beat-producers:
  enabled: true
  common:
    enabled: false
  postgresql:
    enabled: false
  redis:
    enabled: false
  envVars:
    G2P_BRIDGE_CELERY_TASKS_MAPPER_RESOLVE_API_URL: 'http://mapper/sync/resolve'
    G2P_BRIDGE_CELERY_TASKS_DB_HOSTNAME: '{{ .Release.Name }}-postgresql'
    G2P_BRIDGE_CELERY_TASKS_CELERY_BROKER_URL: redis://{{ .Release.Name }}-redis-master:6379/0
    G2P_BRIDGE_CELERY_TASKS_CELERY_BACKEND_URL: redis://{{ .Release.Name }}-redis-master:6379/0

  envVarsFrom:
    G2P_BRIDGE_CELERY_TASKS_DB_PASSWORD:
      secretKeyRef:
        name: '{{ .Release.Name }}-postgresql'
        key: password

openg2p-g2p-bridge-celery-workers:
  enabled: true
  common:
    enabled: false
  postgresql:
    enabled: false
  redis:
    enabled: false
  envVars:
    G2P_BRIDGE_CELERY_WORKERS_MAPPER_RESOLVE_API_URL: 'http://mapper/sync/resolve'
    G2P_BRIDGE_CELERY_WORKERS_MAPPER_RESOLVE_RETRY_DELAY: 5
    G2P_BRIDGE_CELERY_WORKERS_DB_DBNAME: openg2p_g2p_bridge_db
    G2P_BRIDGE_CELERY_WORKERS_DB_HOSTNAME: '{{ .Release.Name }}-postgresql'
    G2P_BRIDGE_CELERY_WORKERS_BANK_FA_DECONSTRUCT_STRATEGY: bank_(?P<account_number>\d+)_(?P<bank_code>\d+)_(?P<branch_code>\d+)_(?P<account_type>\w+)
    G2P_BRIDGE_CELERY_WORKERS_MOBILE_WALLET_DECONSTRUCT_STRATEGY: mobile_(?P<mobile_number>\d+)_(?P<mobile_wallet_provider>\w+)
    G2P_BRIDGE_CELERY_WORKERS_EMAIL_WALLET_DECONSTRUCT_STRATEGY: email_(?P<email_address>\w+)_(?P<email_wallet_provider>\w+)
    G2P_BRIDGE_CELERY_WORKERS_FUNDS_AVAILABLE_CHECK_URL_EXAMPLE_BANK: http://127.0.0.1:8003/check_funds"
    G2P_BRIDGE_CELERY_WORKERS_FUNDS_BLOCK_URL_EXAMPLE_BANK: http://127.0.0.1:8003/block_funds"
    G2P_BRIDGE_CELERY_WORKERS_FUNDS_DISBURSEMENT_URL_EXAMPLE_BANK: http://127.0.0.1:8003/initiate_payment"
    G2P_BRIDGE_CELERY_WORKERS_CELERY_BROKER_URL: redis://{{ .Release.Name }}-redis-master:6379/0
    G2P_BRIDGE_CELERY_WORKERS_CELERY_BACKEND_URL: redis://{{ .Release.Name }}-redis-master:6379/0

  envVarsFrom:
    G2P_BRIDGE_CELERY_WORKERS_DB_PASSWORD:
      secretKeyRef:
        name: '{{ .Release.Name }}-postgresql'
        key: password

postgresql:
  enabled: true
  auth:
    username: bridgeuser
    database: openg2p_g2p_bridge_db
  primary:
    extendedConfiguration: |-
      wal_level = logical
      max_wal_senders = 20
      max_replication_slots = 10

redis:
  cluster:
    enabled: false
  replicaCount: 1
  auth:
    enabled: false
